on: [push]

jobs:
  lua_github_actions_job:
    runs-on: ubuntu-latest
    name: A job to build lua 
    steps:
    - name: Docker
      uses: docker://nirocr/lua_cd
    - uses: actions/checkout@v1
    - name: Where am I
      run: |
        pwd
        ls -al  
    - name: Build
      run: |
        ls -al
        test -f makefile && grep -v "# -pedantic" makefile > makefile2 && mv makefile2 makefile
        make
    
