on: [push]

jobs:
  lua_github_actions_job:
    runs-on: ubuntu-latest
    name: A job to build lua 
    steps:
    - name: Docker
      run: |
        apt-get update && apt-get upgrade -y && apt-get install -y \
            curl \
            wget \
            build-essential \
            make \
            gcc \
            mingw-w64 \
            libreadline-dev \
            ca-certificates \
            unzip \
            libssl-dev \
            git \
            sudo \
            --no-install-recommends
    - uses: actions/checkout@v1
    - name: Where am I
      run: |
        pwd
        ls -al  
    - name: Build
      run: |
        ls -al
        test -f makefile && grep -v "# -pedantic" makefile > makefile2 && mv makefile2 makefile
        make
    
