on: [push]

jobs:
  lua_github_actions_job:
    runs-on: ubuntu-latest
    name: A job to build lua 
    steps:
    
    - name: Dependencies Install
      run: |
        sudo apt-get install -y \
            curl \
            wget \
            build-essential \
            make \
            gcc \
            mingw-w64 \
            libreadline-dev \
            ca-certificates \
            unzip \
            libssl-dev \
            git \
            sudo \
            --no-install-recommends
    
    - uses: actions/checkout@v1
    
    - run: mkdir -p artifacts    
    
    - name: Setup Tools
      env:
       VECTORCAST_DIR: /tmp/vcast
       VECTOR_LICENSE_FILE: 27000@lic.automation-intelligence.com
       VERSION_VECTORCAST: 2018
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y lsb libfontconfig:i386 libxext6:i386 libxrender1:i386 libglib2.0-0:i386
        wget https://s3-eu-west-1.amazonaws.com/drivers.automation-intelligence/VectorCAST/vcast.linux.$VERSION_VECTORCAST.tar.gz
        mkdir -p $VECTORCAST_DIR
        tar -xvf vcast.linux.$VERSION_VECTORCAST.tar.gz -C $VECTORCAST_DIR
        $VECTORCAST_DIR/clicast
    
    - name: Build
      run: |
        ls -al
        test -f makefile && grep -v "# -pedantic" makefile > makefile2 && mv makefile2 makefile
        make
    - name: Build Snoop
      env:
       VECTORCAST_DIR: /tmp/vcast
       VECTOR_LICENSE_FILE: 27000@lic.automation-intelligence.com
       VERSION_VECTORCAST: 2018
      run: |
        make clean
        $VECTORCAST_DIR/vcshell --db=lua_vcdb.db make
        mkdir -p test/artefacts
        mv lua_vcdb.db test/artefacts/
    - name: Unit Testing
      env:
       VECTORCAST_DIR: /tmp/vcast
       VECTOR_LICENSE_FILE: 27000@lic.automation-intelligence.com
       VERSION_VECTORCAST: 2018
       LUA_ROOT: ../../
      run: |
         mkdir -p test/unit
         cd test/unit
         export LUA_ROOT=`pwd`/../.. && $VECTORCAST_DIR/manage --project lua --build-execute --incremental --output inc_results.html
         export LUA_ROOT=`pwd`/../.. && $VECTORCAST_DIR/manage --project lua --full-status=status.html
         export LUA_ROOT=`pwd`/../.. && $VECTORCAST_DIR/manage --project lua --create-report=aggregate
         export LUA_ROOT=`pwd`/../.. && $VECTORCAST_DIR/manage --project lua --create-report=metrics
         export LUA_ROOT=`pwd`/../.. && $VECTORCAST_DIR/manage --project lua --create-report=environment
         export LUA_ROOT=`pwd`/../.. && $VECTORCAST_DIR/manage --project lua --clicast-args report custom management
         export LUA_ROOT=`pwd`/../.. && $VECTORCAST_DIR/manage --project lua --clicast-args report custom actual
         ls -al
         mv *.html ../artefacts

    - uses: actions/upload-artifact@master
      with:
         name: lua-artifact
         path: test/artefacts

